#!/bin/bash
# exit when any command fails
set -e

time (

NEWR=$(mktemp -d -t hook-XXXXXXXXXX)
OUTPUT_BASE=$(mktemp -d -t hook-base-XXXXXXXXXX)

BAZEL="bazel --output_base=$OUTPUT_BASE --nosystem_rc"
TESTS=(
  ...
)

# Create a "clean" client.
cd "$(git rev-parse --show-toplevel)"  # Go to the top
git checkout-index --prefix="${NEWR}/" -a
cd "$NEWR"

if $BAZEL test --config=ci -k -- "${TESTS[@]}";
then
  $BAZEL clean --expunge
else
  echo "file://$NEWR"
  exit 1
fi
)
